version: '3.8'

services:
  model-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      # Mount model directory untuk update model tanpa rebuild
      - ./models:/app/models:ro
      # Mount logs directory
      - ./logs:/app/logs
    networks:
      - model-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - model-network
    # Hapus profiles agar prometheus selalu jalan
    depends_on:
      - model-api

# Grafana service
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # Enable alerting
      - GF_ALERTING_ENABLED=true
      - GF_UNIFIED_ALERTING_ENABLED=true
    networks:
      - model-network
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana  
      # Dashboard files
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro

networks:
  model-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: