version: '3.8'

services:
  model-api:
    image: omapslab/loan_model:latest
    container_name: model-api
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      # Mount model directory untuk update model tanpa rebuild
      - ./models:/app/models:ro
      # Mount logs directory
      - ./logs:/app/logs
    networks:
      - model-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'  

  # Optional: Monitoring dengan Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: model-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - model-network
    profiles:
      - monitoring

networks:
  model-network:
    driver: bridge

volumes:
  prometheus-data: