name: Run Modelling with Local MLflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  modelling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: myenv
          environment-file: conda.yml
          auto-activate-base: false

      - name: Start local MLflow server
        shell: bash -l {0}
        run: |
          # Start MLflow server in background
          mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root ./mlruns &
          echo "MLFLOW_TRACKING_URI=http://localhost:5000" >> $GITHUB_ENV
          
          # Wait for server to start
          sleep 10

      - name: Run modelling with local MLflow
        shell: bash -l {0}
        run: |
          # Run your modelling scripts with local MLflow
          export MLFLOW_TRACKING_URI=http://localhost:5000
          
          python modelling.py
          python feature_analysis.py
          python modelling_tuning.py

      - name: Register model locally
        shell: bash -l {0}
        run: |
          export MLFLOW_TRACKING_URI=http://localhost:5000
          
          python -c "
          import mlflow
          from mlflow.tracking import MlflowClient
          
          client = MlflowClient()
          
          # Get latest run
          experiment = client.get_experiment_by_name('Default')
          runs = client.search_runs(experiment_ids=[experiment.experiment_id], 
                                   order_by=['start_time DESC'], max_results=1)
          
          if runs:
              run_id = runs[0].info.run_id
              model_uri = f'runs:/{run_id}/model'
              
              # Register model
              mlflow.register_model(model_uri, 'loan-model')
              print(f'Model registered from run: {run_id}')
          "

      - name: Build Docker image from local MLflow
        shell: bash -l {0}
        run: |
          export MLFLOW_TRACKING_URI=http://localhost:5000
          
          # Build Docker image using local MLflow
          mlflow models build-docker \
            -m "models:/loan-model/1" \
            -n "${{ secrets.DOCKER_USERNAME }}/loan-model:latest"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/loan-model:latest

      - name: Upload MLflow artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: ./mlruns